import type { GetStaticProps, NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import imageLoader from "../imageLoader";
import styles from "../styles/Home.module.css";
import { Character, GetCharacterResult } from "../types";

const Home: NextPage<{ characters: Character[] }> = ({ characters }) => {
	return (
		<div className={styles.container}>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<main className={styles.main}>
				<h1 className={styles.title}>
					Welcome to <a href="https://nextjs.org">Next.js!</a>
				</h1>

				<p className={styles.description}>
					Get started by editing{" "}
					<code className={styles.code}>pages/index.tsx</code>
				</p>

				<div className={styles.grid}>
					{characters.map((character) => {
						return (
							<div key={character.id}>
								<Link href={`/characters/${character.id}`}>
									<a>
										<h3>{character.name}</h3>
									</a>
								</Link>
								<Image
									loader={imageLoader}
									unoptimized
									src={character.image}
									alt={character.name}
									width={200}
									height={200}
								/>
							</div>
						);
					})}
				</div>
			</main>

			<footer className={styles.footer}>
				<a
					href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
					target="_blank"
					rel="noopener noreferrer"
				>
					Powered by{" "}
					<span className={styles.logo}>
						<Image
							loader={imageLoader}
							unoptimized
							src="/vercel.svg"
							alt="Vercel Logo"
							width={72}
							height={16}
						/>
					</span>
				</a>
			</footer>
		</div>
	);
};

export const getStaticProps: GetStaticProps = async (context) => {
	const res = await fetch("https://rickandmortyapi.com/api/character");

	const { results }: GetCharacterResult = await res.json();

	return {
		props: {
			characters: results,
		},
	};
};

export default Home;
